- hosts: localhost

  roles:
    - { role: base }
    - { role: user, username: 'alexander', password_hash: '{{ hash }}' }
    - { role: docker }
    - { role: desktopenv }
  tasks:
    - block:
      - name: Set the owner of the home directory to the user
        command: chown -R '{{ username }}' '/home/{{ username }}'
      - name: Change files marked executable to 700
        command: find '/home/{{ username }}' -type f -executable -exec chmod 700 {} +
      - name: Change files not marked as executable to 600
        command: find '/home/{{ username }}' -type f -not -executable -exec chmod 600 {} +
      - name: Change all directories to 700
        command: find '/home/{{ username }}' -type d chmod 700 {} +
