- hosts: localhost

  roles:
    - { role: base }
    # As we cannot prepend tasks to certain roles, we just create a role that is
    # our "pre-task" for the role 'user'
    - { role: pre_user, hash: '{{ hash }}' }
    - { role: user, become_user: '{{ username }}', become: yes }
    - { role: docker }
    - { role: desktopenv }
