- hosts: 127.0.0.1
  connection: local
  vars:
    username: 'alexander'

  pre_tasks:
    - name: Setting the default hostname
      set_fact: machine_hostname="tenshi"
    - name: Setting the desktop hostname
      set_fact: machine_hostname="miku"
      when: system == 'desktop'
    - name: Setting the netbook hostname
      set_fact: machine_hostname="mikasa"
      when: system == 'netbook'

  roles:
    - { role: setup, user: '{{ username }}', hostname: '{{ machine_hostname }}', password_hash: '{{ hash }}' }
    - { role: system_desktop, user: '{{ username }}', when: system == 'desktop' }
    - { role: system_netbook, user: '{{ username }}', when: system == 'netbook'}
  tasks:
    - block:
      - name: Set the owner of the home directory to the user
        command: chown -R '{{ username }}' '/home/{{ username }}'
        become: yes
      - name: Change files marked executable to 700
        command: find '/home/{{ username }}' -type f -executable -exec chmod 700 {} +
        become: yes
      - name: Change files not marked as executable to 600
        command: find '/home/{{ username }}' -type f -not -executable -exec chmod 600 {} +
        become: yes
      - name: Change all directories to 700
        command: find '/home/{{ username }}' -type d chmod 700 {} +
        become: yes
