---
- name: Installing spacemacs
  git:
    clone: yes
    repo: 'https://github.com/syl20bnr/spacemacs'
    dest: '{{ home }}/.emacs.d/'

- name: Configuring spacemacs
  file:
    state: link
    src: '{{ role_path }}//files/spacemacs/dotspacemacs'
    dest: '{{ home }}/.spacemacs'

- name: Installing packages for emacs
  block:
    - name: GhostScript for doc-mode
      pacman:
        name: ghostscript
  become_user: root
  become: yes
