---
- block:
    - name: Creating the Development folder
      file:
        state: directory
        path: '{{ home }}/Development/'
        mode: '{{ homedir_fmask }}'
        owner: '{{ username }}'
    - name: Creating the Build directory
      file:
        state: directory
        path: '{{ home }}/Build/'
        mode: '{{ homedir_fmask }}'
        owner: '{{ username }}'

#- name: Enabling service
#  systemd:
#    name: '{{ item }}'
#    user: yes
#    enabled: yes
#  with_items:
#    - 'ssh-agent.service'

- import_tasks: fonts.yml
- import_tasks: editor.yml
- import_tasks: security.yml
- import_tasks: software.yml
