---
# Fonts
- name: Installing fonts
  pacman:
    name: ttf-hack,adobe-source-code-pro-fonts,powerline-fonts

- name: Installing a webbrowser
  pacman:
    name: chromium

- name: Installing a PDF reader
  pacman:
    name: okular

- name: Installing a terminal emulator
  pacman:
    name: termite
