---
- name: Installing sway
  pacman:
    name: sway

- name: Installing qt-wayland (for gpg)
  pacman:
    name: qt5-wayland

- name: Installing a statusbar
  pacman:
    name: i3status

# Create a starter with a German keymap
- block:
    - copy:
        src: '{{ role_path }}/files/sway/sway-de'
        dest: /usr/local/bin/sway-de
        mode: 0555
    - copy:
        src: '{{ role_path }}/files/sway/sway-de.desktop'
        dest: /usr/share/wayland-sessions/sway-de.desktop
        mode: 0444
