---
- name: <de> Installing KDE Plasma and LXQT
  pacman:
    name: plasma,lxqt
  become: yes

- name: <de> Creating LXQT's configuration directory
  file:
    state: directory
    path: '{{ user_home }}/.config/lxqt'

- name: <de> Installing the LXQT configuration
  copy:
    src: '{{ role_path }}/files/lxqt/{{ item }}'
    dest: '{{ user_home }}/.config/lxqt/{{ item }}'
    force: yes
  with_items:
    - lxqt.conf
    - session.conf

- name: <de> Installing urxvt to use it as a launcher
  pacman:
    name: rxvt-unicode
  become: yes
