---
- name: <de> Installing KDE Plasma and LXQT
  pacman:
    name: plasma,lxqt
  become: yes

- name: <de> Creating LXQT's configuration directory
  file:
    state: directory
    path: '{{ user_home }}/.config/lxqt'

- name: <de> Installing the LXQT configuration
  copy:
    src: '{{ role_path }}/files/lxqt/{{ item }}'
    dest: '{{ user_home }}/.config/lxqt/{{ item }}'
    force: yes
  with_items:
    - globalkeyshortcuts.conf
    - lxqt-config.conf
    - lxqt-powermanagement.conf
    - lxqt-runner.conf
    - lxqt.conf
    - notifications.conf
    - panel.conf
    - power.conf
    - session.conf
    - windowmanagers.conf

- name: <de> Installing dunst as a notification server
  pacman:
    name: dunst
  become: yes

- name: <de> Making sure that .config/dunst/ exists
  file:
    state: directory
    path: '{{ user_home }}/.config/dunst/'

- name: <de> Installing dunst configuration
  file:
    state: link
    src: '{{ role_path }}/files/dunst/dunstrc'
    dest: '{{ user_home }}/.config/dunst/dunstrc'
