---
- name: <development> Installing emacs
  pacman:
    name: emacs

- name: <development> Cloning spacemacs
  git:
    clone: yes
    repo: "https://github.com/syl20bnr/spacemacs"
    dest: "{{ user_home }}/.emacs.d"
    
