---
- name: Install i3-gaps' dependencies
  pacman:
    name: pango,libev,libxkbcommon-x11,xcb-util-cursor,xcb-util-keysyms,xcb-util-wm,xcb-util-xrm,yajl,startup-notification

- name: Make sure that the clone directory does not exist
  file:
    state: absent
    path: '{{ user_home }}/Build/i3-gaps'

- name: Clone i3-gaps
  git:
    repo: 'https://github.com/Airblader/i3.git'
    clone: yes
    dest: '{{ user_home }}/Build/i3-gaps'

- block:
  - name: Prepare the build
    command: autoreconf --force --install chdir='{{ user_home }}/Build/i3-gaps'
  - file:
      state: absent
      path: '{{ user_home }}/Build/i3-gaps/build'
  - file:
      state: directory
      path: '{{ user_home }}/Build/i3-gaps/build'
  - name: Configure the build
    command: ../configure --prefix=/usr --sysconfdir=/etc --disable-sanitizers chdir='{{ user_home }}/Build/i3-gaps/build'

- name: Build i3-gaps
  make:
    chdir: '{{ user_home }}/Build/i3-gaps/build'
    params:
      NUM_THREADS: 5

- name: Install i3-gaps
  make:
    chdir: '{{ user_home }}/Build/i3-gaps/build'
    target: install
  become: yes

- name: Create the i3 config directory
  file:
    state: directory
    path: '{{ user_home }}/.config/i3'

- name: Install the i3 config
  file:
    state: link
    src: '{{ role_path }}/files/i3/config'
    dest: '{{ user_home }}/.config/i3/config'
