---
- name: <x11> Installing X11 and xinit
  pacman:
    name: xorg-server, xorg-xinit

- name: <x11> Setting the german keyboard layout
  command: localectl set-x11-keymap de
  become: yes
  ignore_errors: yes
