---
- name: Installing SDDM
  pacman:
    name: sddm
  become: yes

- name: Installing the SDDM config
  copy:
    src: '{{ role_path }}/files/sddm/sddm.conf'
    dest: '/etc/sddm.conf'
  become: yes

- name: Enabling SDDM
  systemd:
    enabled: yes
    state: stopped
  become: yes
