---
- name: <polybar> Install polybar's dependencies
  pacman:
    name: xcb-util-image,xcb-util-wm,xcb-util-xrm

- name: <polybar> Make sure that polybar is not already cloned
  file:
    state: absent
    path: '{{ user_home }}/Build/polybar'

- name: <polybar> Clone polybar's source
  git:
    repo: 'https://github.com/jaagr/polybar.git'
    clone: yes
    recursive: yes
    dest: '{{ user_home }}/Build/polybar'

- block:
    - name: <polybar> Create build directory
      file:
        path: '{{ user_home }}/Build/polybar/build'
        state: directory
    - name: <polybar> Generate the makefile
      command: cmake .. chdir='{{ user_home }}/Build/polybar/build'

- name: <polybar> Build polybar
  make:
    chdir: '{{ user_home }}/Build/polybar/build'
    target: install
    params:
        NUM_THREADS: 5
  become: yes

- block:
    - name: <polybar> Creating polybar's config directory
      file:
        state: directory
        path: '{{ user_home }}/.config/polybar'
    - name: <polybar> Installing the polybar config
      file:
        state: link
        src: '{{ role_path }}/files/polybar/config'
        dest: '{{ user_home }}/.config/polybar/config'
    - name: <polybar> Installing the launch wrapper
      file:
        state: link
        src: '{{ role_path }}/files/polybar/launch.sh'
        dest: '{{ user_home }}/.config/polybar/launch.sh'
        mode: 0700
