---
- name: <pkgs_dockerd> Installing docker
  pacman:
    name: docker
  become: yes

- name: <pkgs_dockerd> Enabling docker
  systemd:
    enabled: yes
    state: started
    name: docker
  become: yes
  ignore_errors: yes

# We use systemd, so it's needed
- name: <pkgs_dockerd> Create docker's configuration directory
  file:
    state: directory
    path: /usr/systemd/system/docker.service.d

- name: <pkgs_dockerd> Install custom daemon settings
  copy:
    src: '{{ role_path }}/files/no_icc.conf'
    dest: /usr/systemd/system/docker.service.d/no_icc.conf
    mode: 0644
