---
- name: <netbook> Installing network tools (nmap, ...)
  pacman:
    name: nmap
  become: yes

- name: <netbook> Installing i3lock
  pacman: 
    name: i3lock
  become: yes

- include: term.yml
- include: neovim.yml
- include: multimedia.yml

- block:
  - name: <netbook> Installing the brightness script
    copy:
      src: '{{ role_path }}/files/scripts/bright'
      dest: /usr/local/bin/bright
      mode: 0755
    become: yes
  - name: <netbook> Installing the lock script (Workaround for the zsh suspend)
    copy:
      src: '{{ role_path }}/file/scripts/lock'
      dest: /usr/local/bin/lock
      mode: 0755
    become: yes
