---
- name: <iptables> Installing the iptable tools
  pacman:
    name: iptables

- block:
    - name: <iptables> Applying iptable rules
      iptables:
        chain: INPUT
        policy: DROP
      # Accept packets from connections we initiated
    - iptables:
        chain: INPUT
        action: append
        ctstate: ESTABLISHED
        jump: ACCEPT
      # Accept packets coming from localhost to localhost
    - iptables:
        chain: INPUT
        action: append
        source: 127.0.0.1
        destination: 127.0.0.1
        jump: ACCEPT

# systemd only!
- block:
    - name: <iptables> Saving the iptable rules
      shell: iptables-save > /etc/iptables/iptables.rules
    - name: <iptables> Starting and enabling the iptables service
      systemd:
        daemon_reload: yes
        enabled: yes
        name: iptables
      ignore_errors: yes
