---
- name: Setting secure kernel parameters
  copy:
    src: '{{ role_path }}/files/kernel/51-kernel.conf'
    dest: /etc/sysctl.d/51-kernel.conf
    mode: 0644
  become: yes

- block:
    - name: Installing hidepid
      pacman:
        name: hidepid
      become: yes
    - name: Enabling and starting hidepid
      systemd:
        enabled: yes
        state: started
        name: hidepid.service
      become: yes
