---
- name: Setting the hostname
  hostname:
    name: '{{ hostname }}'

- name: Installing NetworkManager
  pacman:
    name: networkmanager
  become: yes

- name: Disabling ipv6
  copy:
    src: '{{ role_path }}/files/kernel/50-network.conf'
    dest: /etc/sysctl.d/50-network.conf
    mode: 0644
  become: yes
