---
- name: Install zsh
  pacman:
    name: zsh

- name: Install the configuration of zsh (and bash)
  file:
    state: link
    src: '{{ role_path  }}/files/zsh/{{ item }}'
    dest: '{{ user_home }}/.{{ item }}'
  with_items:
     - zshrc
     - bashrc

