---
- name: Setting the hostname
  shell: echo '{{ hostname }}' > /etc/hostname
  become: yes

- name: Adding the hostname to /etc/hosts
  shell: echo '127.0.0.1        local.{{ hostname }} {{ hostname }}' >> /etc/hosts
  become: yes

- name: Installing NetworkManager
  pacman:
    name: networkmanager
  become: yes

- name: Enabling NetworkManager
  systemd:
    state: stopped
    enabled: yes
    name: NetworkManager
  become: yes

- name: Disabling ipv6
  copy:
    src: '{{ role_path }}/files/kernel/50-network.conf'
    dest: /etc/sysctl.d/50-network.conf
    mode: 0644
  become: yes
