---
- name: <user> Creating a sudo group
  group:
    state: present
    name: sudo

- name: <user> Creating a dockerservuser group
  group:
    state: present
    name: dockerservuser

- name: <user> Creating a user account
  user:
    groups: sudo,dockerservuser
    createhome: yes
    state: present
    name: '{{ user }}'
    password: '{{ password_hash }}'
