---
# TODO: Make a slimmed down version for the desktop, too
- name: Installing btrfs
  pacman:
    name: btrfs-progs
  when: group == 'laptop'
- name: Copying slimmed down initcpio
  copy:
    src: '{{ role_path }}/files/mkinitcpio.laptop'
    dest: /etc/mkinitcpio.conf
    force: yes
  when: group == 'laptop'
- name: Regenerate initramfs
  command: mkinitcpio -p linux
  when: group == 'laptop'

- import_tasks: network.yml
- import_tasks: security.yml
- import_tasks: packages.yml
- import_tasks: gpu.yml
- import_tasks: cpu.yml
- import_tasks: systemd.yml
